"""update session token lifecycle

Revision ID: 23f050738acb
Revises: 7bcdf81d1f4c
Create Date: 2026-08-14 22:47:30.368615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23f050738acb'
down_revision: Union[str, Sequence[str], None] = '7bcdf81d1f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sessions', sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sessions', sa.Column('access_revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('refresh_revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('sessions', 'revoked_at')
    op.drop_column('sessions', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'refresh_revoked_at')
    op.drop_column('sessions', 'access_revoked_at')
    op.drop_column('sessions', 'refresh_expires_at')
    op.drop_column('sessions', 'access_expires_at')
    # ### end Alembic commands ###
